# 公共配置
spring:
  application:
    name: Lilemy-answer
  # 默认 dev 环境
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000